---
- name: Grab /etc/os-release
  set_fact:
    os_release: "{{ lookup('file','/etc/os-release') }}"

- name: Set rpmfusion repo name
  set_fact:
    rpmfusion_kind: |-
      {%- if 'rawhide' in os_release -%}
      rawhide
      {%- else -%}
      {{- lookup('pipe','rpm -E %fedora') -}}
      {%- endif -%}

- name: Install RPMFusion Free
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ rpmfusion_kind }}.noarch.rpm"
  become: true

- name: Install RPMFusion NonFree
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ rpmfusion_kind }}.noarch.rpm"
  become: true

- name: Install tainted repos
  dnf:
    name:
      - rpmfusion-free-release-tainted
      - rpmfusion-nonfree-release-tainted
  become: true
