---
- name: Install RPMFusion Free
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ lookup('pipe','rpm -E %fedora') }}.noarch.rpm"
  become: true

- name: Install RPMFusion NonFree
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-nonfree-release-{{ lookup('pipe','rpm -E %fedora') }}.noarch.rpm"
  become: true

- name: Install tainted repos
  dnf:
    name:
      - rpmfusion-free-release-tainted
      - rpmfusion-nonfree-release-tainted
  become: true
