---
- hosts: localhost
  connection: local
  become: false
  tasks:
    # vscode
    ## Get settings
    - name: Get Visual Studio Code configuration
      slurp:
        src: "{{ ansible_user_dir }}/.config/Code/User/settings.json"
      register: vscode_config
    - name: Parse Visual Studio Code extensions
      command: code --list-extensions
      changed_when: false
      register: vscode_installed_extensions
    ## Write settings
    - name: Build backup data structure for Visual Studio Code
      set_fact:
        vscode_backup:
          vscode_configuration: "{{ vscode_config['content'] | b64decode | from_json }}"
          vscode_extensions: "{{ vscode_installed_extensions['stdout_lines'] }}"
    - name: Write out the new Visual Studio Code settings file
      copy:
        content: "{{ vscode_backup | to_nice_yaml }}"
        dest: "{{ playbook_dir }}/roles/vscode/defaults/main.yml"
        force: true