---
- hosts: localhost
  connection: local
  roles:
    - { name: containers, tags: [ "containers" ] }
    - { name: flatpak, tags: [ "flatpak" ] }
    - { name: fonts, tags: [ "fonts" ] }
    - { name: k8s, tags: [ "k8s" ] }
    - { name: shells, tags: [ "shells" ] }
    - { name: sudo, tags: [ "sudo" ] }
    - { name: vagrant, tags: [ "vagrant" ] }
    - { name: visual-studio-code, tags: [ "visual-studio-code" ] }
    - { name: tools, tags: [ "tools" ] }
