---
- hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: Install playbook prerequisites
      dnf:
        name:
          - python-psutil
- hosts: localhost
  connection: local
  become: false
  roles:
    # System
    - enable-passwordless-sudo
    - kernel/modules
    - kernel/parameters
    - locale
    - rpmfusion
    # Applications
    - apps
    - coding
    - containerization
    - git
    - gnome
    - k8s
    - vagrant
    - vscode
    - zsh
