---
- hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: Install playbook prerequisites
      dnf:
        name:
          - python-psutil
- hosts: localhost
  connection: local
  become: false
  vars:
    fedora_rawhide: "{{ lookup('file','/etc/os-release') is search('rawhide') }}"
  roles:
    # System
    - { name: enable-passwordless-sudo, tags: [ "enable-passwordless-sudo" ] }
    - { name: kernel, tags: [ "kernel" ] }
    - { name: locale, tags: [ "locale" ] }
    - { name: rpmfusion, tags: [ "rpmfusion" ] }
    # Applications
    - { name: apps, tags: [ "apps" ] }
    - { name: coding, tags: [ "coding" ] }
    - { name: containerization, tags: [ "containerization" ] }
    - { name: git, tags: [ "git" ] }
    - { name: gnome, tags: [ "gnome" ] }
    - { name: k8s, tags: [ "k8s" ] }
    - { name: vagrant, tags: [ "vagrant" ] }
    - { name: vscode, tags: [ "vscode" ] }
    - { name: zsh, tags: [ "zsh" ] }
