---
- name: Create PulseAudio configuration directory
  file:
    path: "{{ ansible_user_dir }}/.config/pulse"
    state: directory

- name: Get PulseAudio resamplers
  command: pulseaudio --dump-resample-methods
  changed_when: false
  register: pulseaudio_resamplers
- name: Ensure resampler is supported
  assert:
    that: pulseaudio_resample_method in pulseaudio_resamplers['stdout_lines']

- name: Template PulseAudio configuration
  template:
    src: daemon.conf
    dest: "{{ ansible_user_dir }}/.config/pulse"
