---
- name: Create dconf database directory
  file:
    path: /etc/dconf/db/database.d
    state: directory
  become: true
- name: Write dconf settings
  assemble:
    src: "{{ role_path }}/files" # Generate with `dconf dump /`
    dest: /etc/dconf/db/database.d/ansible
  notify:
    - Update dconf database
    - Import dconf keys
  become: true
