---
- name: Install Vagrant
  dnf:
    name:
      - vagrant
      - vagrant-libvirt
      - vagrant-sshfs
  become: true

- name: Create .vagrant.d
  file:
    path: "{{ ansible_user_dir }}/.vagrant.d"
    state: directory

- name: Copy default Vagrantfile
  copy:
    src: Vagrantfile
    dest: "{{ ansible_user_dir }}/.vagrant.d"
    force: true
