---
minikube_version: v1.14.1
minikube_settings:
  vm-driver: kvm2
  cpus: "{{ [ 2, ((ansible_processor_vcpus / 2) | int) ] | max }}"
  disk-size: 50G
  memory: "{{ [ 4000, ((ansible_memtotal_mb / 2) | int) ] | max }}"
helm_version: v3.4.0
