---
# Check Jsonnet version
- name: Check Jsonnet version
  command: jsonnet --version
  register: jsonnet_installed_version
  changed_when: false
  failed_when: false
- name: Remove outdated jsonnet binary
  file:
    path: "/usr/local/bin/{{ item }}"
    state: absent
  when: (jsonnet_installed_version['rc'] == 0) and (jsonnet_installed_version['stdout'].split(' ')[3] is version(jsonnet_version ,'<'))
  become: true
  loop:
    - jsonnet
    - jsonnetfmt
# Install
- name: "Install Jsonnet {{ jsonnet_version }}"
  unarchive:
    src: "https://github.com/google/jsonnet/releases/download/{{ jsonnet_version }}/jsonnet-bin-{{ jsonnet_version }}-linux.tar.gz"
    creates: "/usr/local/bin/{{ item }}"
    dest: /usr/local/bin
    mode: 0755
    remote_src: true
    extra_opts:
      - "{{ item }}"
  become: true
  loop:
    - jsonnet
    - jsonnetfmt
