---
- name: Grab /etc/os-release
  set_fact:
    os_release: "{{ lookup('file','/etc/os-release') }}"

- name: Install RPMFusion Free
  dnf:
    name: "http://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ lookup('pipe','rpm -E %fedora') }}.noarch.rpm"
    disable_gpg_check: true
  become: true

- name: Install RPMFusion NonFree
  dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ lookup('pipe','rpm -E %fedora') }}.noarch.rpm"
    disable_gpg_check: true
  become: true
