---
- name: Parse Visual Studio Code current YAML
  set_fact:
    vscode: "{{ lookup('file', playbook_dir + '/roles/visual-studio-code/defaults/main.yml') | from_yaml }}"
- name: Parse Visual Studio Code settings
  set_fact:
    vscode: "{{ vscode | combine(extra) }}"
  vars:
    extra:
      vscode_settings: "{{ lookup('file', ansible_user_dir + '/.config/Code/User/settings.json') | from_json }}"
- name: Rewrite Visual Studio Code defaults YAML
  copy:
    content: "{{ vscode | to_nice_yaml(indent = 2, width = 1337) }}"
    dest: "{{ playbook_dir }}/roles/visual-studio-code/defaults/main.yml"
