---
- name: Get Helm version
  command: helm version --short
  register: helm_version_check
  changed_when: false
  failed_when: false

- block:
    - name: Create tempdir
      tempfile:
        state: directory
      register: temp
    - name: "Download Helm {{ helm_version }}"
      unarchive:
        src: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
        dest: "{{ temp['path'] }}"
        remote_src: true
    - name: "Install Helm {{ helm_version }}"
      copy:
        src: "{{ temp['path'] }}/linux-amd64/helm"
        dest: /usr/local/bin/helm
        remote_src: true
        mode: 0755
        force: true
  always:
    - name: Delete tempdir
      file:
        path: "{{ temp['path'] }}"
        state: absent
  become: true
  when: (helm_version_check['rc'] != 0)
    or (helm_version_check['stdout'].split('+')[0] != helm_version)