---
- import_tasks: remotes.yml

- name: Install flatpaks
  flatpak:
    name: "{{ item[1] }}"
    remote: "{{ item[0]['repo'] }}"
  with_subelements:
    - "{{ flatpaks }}"
    - packages
  loop_control:
    label: "{{ item[1] }}"
