---
- name: Configure Git
  git_config:
    name: "{{ item['key'] }}"
    value: "{{ item['value'] }}"
    scope: global
  with_dict: "{{ git_settings }}"
  loop_control:
    label: "{{ item['key'] }}"
