---
#
# Bash
#
- name: Install BASH
  dnf:
    name:
      - bash
      - bash-completion
  become: true
- name: Template .bashrc
  template:
    src: bashrc.bash
    dest: "{{ ansible_user_dir }}/.bashrc"
#
# FISH
#
- name: Install FISH
  dnf:
    name: fish
  become: true
- name: Create FISH config directory
  file:
    path: "{{ ansible_user_dir }}/.config/fish"
    state: directory
- name: Configure FISH
  template:
    src: config.fish
    dest: "{{ ansible_user_dir }}/.config/fish"
# Set user shell
- name: "Set user shell to fish"
  user:
    name: "{{ ansible_user }}"
    shell: "{{ lookup('pipe', 'which fish') }}"
  become: true
