---
gnome_dconf:
  /org/gnome/desktop/interface/clock-show-seconds: "true"
  /org/gnome/desktop/interface/show-battery-percentage: "true"
  /org/gnome/desktop/peripherals/touchpad/tap-to-click: "true"
  /org/gnome/desktop/privacy/old-files-age: 7
  /org/gnome/desktop/privacy/recent-files-max-age: 7
  /org/gnome/desktop/privacy/remove-old-temp-files: "true"
  /org/gnome/desktop/privacy/remove-old-trash-files: "true"
  /org/gnome/desktop/wm/preferences/button-layout: "'appmenu:minimize,maximize,close'"
  /org/gnome/nautilus/preferences/show-create-link: "false"
  /org/gnome/nautilus/preferences/show-delete-permanently: "false"
  /org/gnome/settings-daemon/plugins/color/night-light-enabled: "true"
  /org/gnome/shell/favorite-apps: "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Software.desktop']"
  /org/gnome/shell/enabled-extensions: "['background-logo@fedorahosted.org', 'disconnect-wifi@kgshank.net', 'nohotcorner@azuri.free.fr', 'places-menu@gnome-shell-extensions.gcampax.github.com', 'refresh-wifi@kgshank.net', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'TopIcons@phocean.net', 'apps-menu@gnome-shell-extensions.gcampax.github.com']"