---
package_list:
  # RPMFusion
  - ffmpeg
  # Programming
  - nodejs
  # CLI
  - ansible
  - aria2
  - asciinema
  - bat
  - curl
  - fzf
  - git
  - glances
  - ht
  - htop
  - hyperfine
  - jq
  - ncdu
  - neovim
  - podman
  - podman-compose
  - pv
  - ranger
  - rclone
  - ripgrep
  - rsync
  - sshfs
  - starship
  - tar
  - tmux
  - tokei
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - zstd
  - python-neovim
  # GUI
  - chromium
  - firefox
  - gnome-latex
  - gnome-firmware

xdg_config: "{{ ansible_user_dir }}/.config"

package_files:
  vagrant/Vagrantfile: "{{ ansible_user_dir }}/.vagrant.d/Vagrantfile"
  starship/starship.toml: "{{ xdg_config }}/starship.toml"
  neovim/init.vim: "{{ xdg_config }}/nvim/init.vim"
  code/settings.json: "{{ xdg_config }}/Code/User/settings.json"
