---
- name: Enable Eclipse module
  command: dnf module enable -y eclipse:latest
  changed_when: false
  become: true
  when: not fedora_rawhide

- name: Install compilers, IDEs and tools for development
  dnf:
    name:
      # Compilers / Interpreters / JIT / YouNameIt
      ## Java
      - java-latest-openjdk
      # IDEs
      ## Eclipse
      - eclipse-egit # Eclipse git integration
      - eclipse-jdt # Eclipse Java tools
      - eclipse-mpc # Marketplace
      # Linter
      - ShellCheck
      - python-autopep8
      - python-pylint
      # Tool
      - make
  become: true

- name: Check Rustup presence
  stat:
    path: "{{ ansible_user_dir }}/.cargo/bin/rustup"
  register: rustup

- name: Install Rust
  shell: >-
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
  when: not rustup['stat']['exists']