---
# Install Visual Studio Code if needed
- import_tasks: install.yml
# Install extensions
- name: List Visual Studio Code extensions
  command: code --list-extensions
  changed_when: false
  register: vscode_installed_exts

- name: Install Visual Studio Code extensions
  command: "code --force --install-extension {{ item }}"
  loop: "{{ vscode_extensions | difference(vscode_installed_exts['stdout_lines']) }}"

- name: Remove extraneous Visual Studio Code extensions
  command: "code --uninstall-extension {{ item }}"
  loop: "{{ vscode_installed_exts['stdout_lines'] | difference(vscode_extensions) }}"
