---
# Defined properties
module_per_machine_settings: {}
module_global_settings: {}
# Calculated properties
module_settings: >-
  {%- if ansible_hostname in module_per_machine_settings -%}
  {{- module_global_settings | combine(module_per_machine_settings[ansible_hostname]) -}}
  {%- else -%}
  {{- module_global_settings -}}
  {%- endif -%}
