name: CI

on:
  push:
    paths:
      - backup.yml

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - name: ansible-lint
      uses: ansible/ansible-lint-action@v4.1.0.post0
      with:
        targets: "backup.yml"
