---
- name: Install ZSH
  dnf:
    name:
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
  become: true

- name: Parse ZSH functions
  set_fact:
    zsh_functions: "{{ zsh_functions | default({})  | combine({ (item | basename) : lookup('template', item) }) }}"
  with_fileglob: "{{ role_path }}/templates/functions/*.zsh"
  loop_control:
    label: "{{ item | basename }}"

- name: Template .zshrc
  template:
    src: zshrc.zsh
    dest: "{{ ansible_user_dir }}/.zshrc"

- name: Set ZSH as user shell
  user:
    name: "{{ ansible_user }}"
    shell: "{{ lookup('pipe', 'which zsh') }}"
  become: true
